### PR TITLE
Add Kazakh translation.

### PR DESCRIPTION
**Pull request by crayxt**
Kazakh translation added.

### CODE REVIEW

**Comment by crayxt** [comment]
I've added the same changes to https://github.com/BitJam/antiX-Gfxboot but it seems like letter `Қ қ` is missing in boot menu. Please re-generate font to include it as well. Thanks,

**Comment by crayxt** [comment]
Hi, any news on this?

**Comment by wfeldt** [comment]
Sorry, somehow slipped my attention. Will integrate asap.

**Comment by crayxt** [comment]
@wfeldt Hi, any news on this request? Thanks,

**Comment by wfeldt** [comment]
Argh! I thought I already did it. My apologies; will look at it right away.

**Pull request merged**
