### PR TITLE
Migrate to new kbd also in gfxboot

### PR DESCRIPTION
**Pull request by shundhammer**
## Trello

https://trello.com/c/8rywZ6js/2810-1-feature-kbd-in-gfxboot

Related:

- Linuxrc: https://trello.com/c/4sCajesT/
- yast-country: https://trello.com/c/9h9b7rws/

## Jira

https://jira.suse.com/browse/SLE-21107

## Description

The _kbd-legacy_ package will be dropped soon, so we need to migrate to the new _kbd_ package where some keymap codes are now different. Some are just renamed; othes are not available yet or not at all.

Here the important part is to use the new keymap names that YaST now expects.

## Migration Documentation

https://github.com/yast/yast-country/blob/master/dropping_kbd_legacy.md

## YaST Keyboards Table

https://github.com/yast/yast-country/blob/master/dropping_kbd_legacy.md

## Unavailable Keymaps

What about those keymaps that are not available anymore now with the new _kbd_?

- arabic
- gr
- khmer
- ruwin_alt-UTF-8
- ~slovak-qwerty~  (**Update:** already changed to _sk-qwerty_ in the code)
- tj_alt-UTF8
- ua-utf

Right now they are still in the tables here. Should we remove them? Or hope that there will be an adequate counterpart in the _kbd_ package in the forseeable future?

### CODE REVIEW

**Comment by mvidner** [comment]
> What about those keymaps that are not available anymore now with the new kbd?
> 
> Right now they are still in the tables here. Should we remove them? Or hope that there will be an adequate counterpart in the kbd package in the forseeable future?

I have filed https://bugzilla.suse.com/show_bug.cgi?id=1194609 for them, which is linked from [dropping_kbd_legacy](https://github.com/yast/yast-country/blob/master/dropping_kbd_legacy.md). IMHO kbd.rpm must acquire them.

>     arabic
>     khmer

These are just symlinks to `us`. Uncontroversial.

>     gr
>     ruwin_alt-UTF-8
>     tj_alt-UTF8
>     ua-utf

These are the non-Latin ones that can be copied or symlinked.

>     slovak-qwerty

Simply use `sk-qwerty`

**Comment by shundhammer** [comment]
I just saw that I already changed `slovak-querty` to `sk-querty`. OK for that one now.

**Comment by shundhammer** [comment]
I also started to add _Dvorak for Programmers_; it's easy enough to add the entry to be transported to YaST, but I don't know about the separate diff that is used for this _gfxboot_ package; something like [keymap.dvorak.inc](https://github.com/openSUSE/gfxboot/blob/master/themes/openSUSE/keymaps/keymap.dvorak.inc).

I guess that's only needed for editing the kernel command line here in the Grub menu. While maybe we could add it with some effort, IMHO a user can also simply select it in the YaST keyboard selection.

**Comment by wfeldt** [comment]
lgtm

**Pull request merged**
